"""SEC-APIKEY-1 (Sprint 1): per-purpose API keys with O(1) lookup.

Adds the ``key_id`` column to ``integration_clients`` and backfills
existing rows. The column is a short, random, public identifier
that the client sends on every request (e.g. ``kid_3f8a9b2c1d0e4f5a``)
so the auth path is O(1) instead of the previous O(n) full-table
scan + HMAC comparison against every active client.

Operational notes
-----------------
* The ``key_id`` is generated by the migration for existing rows
  via ``encode(gen_random_bytes(8), 'hex')`` (Postgres) or
  ``lower(hex(randomblob(8)))`` (SQLite, for tests).
* New clients created via ``POST /admin/integration-clients`` get a
  ``key_id`` assigned at insert time.
* The column is added as ``nullable=True`` so the migration can
  backfill it; once the backfill is done we tighten it to
  ``nullable=False`` in a follow-up migration once all callsites
  are updated to populate it.
* Downgrade: drops the column and its index.
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "0027_integration_clients_key_id"
down_revision = "0025_ocr_engine_version"
branch_labels = None
depends_on = None


def _generate_key_id_sqlite() -> str:
    """Generate a 16-hex-char key id for SQLite (used in tests)."""
    # ``randomblob(8)`` returns 8 raw bytes; ``hex()`` gives 16 hex
    # chars. ``lower()`` keeps things consistent across engines.
    return "kid_" + sa.text("lower(hex(randomblob(8)))").compile()


def upgrade() -> None:
    # 1. Add the column nullable so the backfill can run before
    #    tightening the constraint.
    with op.batch_alter_table("integration_clients") as batch:
        batch.add_column(
            sa.Column(
                "key_id",
                sa.String(length=32),
                nullable=True,
            )
        )

    # 2. Backfill: generate a 16-hex-char id per existing row.
    #    The literal "kid_" prefix is intentional: it makes the
    #    field self-describing in logs and lets a regex (if ever
    #    needed) distinguish it from a raw secret.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute(
            sa.text(
                "UPDATE integration_clients "
                "SET key_id = 'kid_' || encode(gen_random_bytes(8), 'hex') "
                "WHERE key_id IS NULL"
            )
        )
    else:
        # SQLite (used by tests via ``sqlite+pysqlite:///:memory:``).
        op.execute(
            sa.text(
                "UPDATE integration_clients "
                "SET key_id = 'kid_' || lower(hex(randomblob(8))) "
                "WHERE key_id IS NULL"
            )
        )

    # 3. Add the unique index now that the column is populated.
    op.create_index(
        "ix_integration_clients_key_id",
        "integration_clients",
        ["key_id"],
        unique=True,
    )

    # 4. Tighten the column to NOT NULL. Operators with pre-existing
    #    legacy clients without key_id would have failed the
    #    backfill above and stopped the migration; this line is
    #    safe to run because every row is populated.
    with op.batch_alter_table("integration_clients") as batch:
        batch.alter_column("key_id", existing_type=sa.String(32), nullable=False)


def downgrade() -> None:
    with op.batch_alter_table("integration_clients") as batch:
        batch.drop_index("ix_integration_clients_key_id")
        batch.drop_column("key_id")
